// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EventDefine.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Pb
{

    [global::ProtoBuf.ProtoContract()]
    public enum EGameMsgID
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EGMI_UNKNOW")]
        EgmiUnknow = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EGMI_LOGIN_REQ")]
        EgmiLoginReq = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EGMI_LOGIN_RESPON")]
        EgmiLoginRespon = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EGMI_CONNECT_TO_GATE_REQ")]
        EgmiConnectToGateReq = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"EGMI_CONNECT_TO_GATE_RESPON")]
        EgmiConnectToGateRespon = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"EGMI_SINGLE_MSG_START")]
        EgmiSingleMsgStart = 10000,
    }

    [global::ProtoBuf.ProtoContract(Name = @"SERVER_TYPE")]
    public enum ServerType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"START")]
        Start = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MACHINE")]
        Machine = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN")]
        Login = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"GATE")]
        Gate = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"CENTER")]
        Center = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIC")]
        Logic = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"END")]
        End = 6,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
