// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: game_msg.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Pb
{

}

#pragma warning restore CS1591, CS0612, CS3021
