// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: MsgDefine.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Pb
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"gate_addr")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GateAddr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"respon_code")]
        public LoginResponCode ResponCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectToGateReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectToGateRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"respon_code")]
        public ConnectToGateResponCode ResponCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleInfo
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlayerName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleListReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoleListRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"role_list")]
        public global::System.Collections.Generic.List<RoleInfo> RoleLists { get; } = new global::System.Collections.Generic.List<RoleInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoleReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoleRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"respon_code")]
        public CreateRoleResponCode ResponCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterGameReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EnterGameRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"respon_code")]
        public EnterGameResponCode ResponCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveGameReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaveGameRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"respon_code")]
        public LeaveGameResponCode ResponCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoomReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CreateRoomRespon
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public uint PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"room_id")]
        public uint RoomId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"respon_code")]
        public CreateRoomResponCode ResponCode { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum LoginResponCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_SUCCESS")]
        LoginSuccess = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LOGIN_FAIL")]
        LoginFail = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ConnectToGateResponCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECT_TO_GATE_SUCCESS")]
        ConnectToGateSuccess = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECT_TO_GATE_FAIL")]
        ConnectToGateFail = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CreateRoleResponCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CREATE_ROLE_SUCCESS")]
        CreateRoleSuccess = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CREATE_ROLE_FAIL")]
        CreateRoleFail = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EnterGameResponCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_GAME_SUCCESS")]
        EnterGameSuccess = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ENTER_GAME_FAIL")]
        EnterGameFail = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LeaveGameResponCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LEAVE_GAME_SUCCESS")]
        LeaveGameSuccess = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LEAVE_GAME_FAIL")]
        LeaveGameFail = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CreateRoomResponCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"CREATE_ROOM_SUCCESS")]
        CreateRoomSuccess = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CREATE_ROOM_FAIL")]
        CreateRoomFail = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
